/** TypeScript facade for shared system email templates (.mjs). */
export {
  buildSignupVerificationEmail,
  buildPasswordResetEmail,
  buildOutsideGeofenceVerificationEmail,
  buildSmtpTestEmail,
  buildPortalCredentialEmail,
  buildStaffInviteEmail,
  buildStaffPasswordResetEmail,
  buildBackupNotificationEmail,
  buildDailySummaryEmail,
  buildInvoiceAttachedEmail,
  buildNotifyChannelChangedEmail,
  buildLoginNotificationEmail,
  buildCustomerAutoResponderEmail,
  buildDeletionRequestSubmittedEmail,
  buildDeletionRequestResultEmail,
  buildUserSignupPendingEmail,
  buildInvoicePendingApprovalEmail,
  buildCustomerServiceRequestStaffEmail,
  buildCustomerChangeRequestStaffEmail,
  buildCustomerEmailReceivedStaffEmail,
  buildChatMessageReceivedEmail,
} from './system.mjs'
