/** Re-export service log extraction rule helpers for TypeScript consumers. */
export {
  DEFAULT_SERVICE_LOG_EXTRACTION_RULE_CARDS,
  DEFAULT_SERVICE_LOG_EXTRACTION_RULES,
  SERVICE_LOG_HIGH_CERTAINTY_THRESHOLD,
  SERVICE_LOG_SHEET_MATCH_THRESHOLD,
  normalizeServiceLogExtractionRules,
  flattenActiveSheetItems,
  formatActiveSheetCatalogForPrompt,
  sheetPriceToRate,
  sheetItemNameSimilarity,
  matchDraftLineToSheetItem,
  isSheetLockedPage,
  requiresHighCertaintyLines,
  buildPageTypeSystemPrompt,
  buildPageTypeUserPrompt,
  buildExtractionSystemPrompt,
  buildExtractionUserPrompt,
  mergeServiceLogPageExtractions,
  normalizePageType,
} from './service-log-extraction-rules.mjs'
