export {
  STAPLES_PRINTME_TO,
  STAPLES_PRINTME_SUBJECT_PREFIX,
  STAPLES_PRINTME_TOKEN_RE,
  STAPLES_PRINTME_CODE_TTL_MS,
  STAPLES_PRINTME_LOCATOR_URL,
  STAPLES_PRINTME_IMAP_POLL_MS,
  STAPLES_PRINT_JOB_STATUSES,
  normalizePrintMeAddress,
  isPrintMeSender,
  buildPrintMeSubject,
  buildPrintMeTextBody,
  assertPrintMePdfAttachment,
  buildPrintMeMailPayload,
  extractPrintMeSubjectToken,
  extractPrintMeReleaseCode,
  pickPrintMeBarcodeAttachment,
  buildCode128Svg,
  replyMatchesPrintMeJob,
} from './staples-printme.mjs'
